export const useGhGist = jest.fn(() => ({ data: undefined, isLoading: false, isError: false }))
export const useGhCreateGist = jest.fn(() => ({ mutate: jest.fn(), mutateAsync: jest.fn(), isPending: false }))
export const useGhUpdateGist = jest.fn(() => ({ mutate: jest.fn(), mutateAsync: jest.fn(), isPending: false }))
export const useGhDeleteGist = jest.fn(() => ({ mutate: jest.fn(), mutateAsync: jest.fn(), isPending: false }))
export const useGhUser = jest.fn(() => ({ data: undefined, isLoading: false }))
