/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MaintainersRouteImport } from './routes/maintainers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesNameRouteImport } from './routes/packages.$name'
import { Route as MaintainersUsernameRouteImport } from './routes/maintainers_.$username'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintainersRoute = MaintainersRouteImport.update({
  id: '/maintainers',
  path: '/maintainers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesNameRoute = PackagesNameRouteImport.update({
  id: '/packages/$name',
  path: '/packages/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintainersUsernameRoute = MaintainersUsernameRouteImport.update({
  id: '/maintainers_/$username',
  path: '/maintainers/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/maintainers': typeof MaintainersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/maintainers/$username': typeof MaintainersUsernameRoute
  '/packages/$name': typeof PackagesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/maintainers': typeof MaintainersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/maintainers/$username': typeof MaintainersUsernameRoute
  '/packages/$name': typeof PackagesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/maintainers': typeof MaintainersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/maintainers_/$username': typeof MaintainersUsernameRoute
  '/packages/$name': typeof PackagesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/maintainers'
    | '/profile'
    | '/settings'
    | '/sync'
    | '/maintainers/$username'
    | '/packages/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/maintainers'
    | '/profile'
    | '/settings'
    | '/sync'
    | '/maintainers/$username'
    | '/packages/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/maintainers'
    | '/profile'
    | '/settings'
    | '/sync'
    | '/maintainers_/$username'
    | '/packages/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MaintainersRoute: typeof MaintainersRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  MaintainersUsernameRoute: typeof MaintainersUsernameRoute
  PackagesNameRoute: typeof PackagesNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintainers': {
      id: '/maintainers'
      path: '/maintainers'
      fullPath: '/maintainers'
      preLoaderRoute: typeof MaintainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$name': {
      id: '/packages/$name'
      path: '/packages/$name'
      fullPath: '/packages/$name'
      preLoaderRoute: typeof PackagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintainers_/$username': {
      id: '/maintainers_/$username'
      path: '/maintainers/$username'
      fullPath: '/maintainers/$username'
      preLoaderRoute: typeof MaintainersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MaintainersRoute: MaintainersRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  MaintainersUsernameRoute: MaintainersUsernameRoute,
  PackagesNameRoute: PackagesNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
